### ISSUE TITLE
Video with no audio

### ISSUE THREAD

**Issue by FernandoDiCostanzo** [Cle3000/FFmpegVideoComponent-for-JUCE#1]
When you try to load a video ( in my case .mp4 ) it doesn't work.

**Comment by himwho** [comment]
inversely audio with no video also isnt accepted

**Comment by himwho** [comment]
I have extended this project to allow audio only files and video without audio, @Cle3000  if the following is accepted: https://github.com/Cle3000/FFmpegVideoComponent-for-JUCE/pull/2 I can make a second PR with those new changes to fix this too

**Comment by Cle3000** [comment]
@FernandoDiCostanzo Thank you for pointing this out. 
@himwho I merged your edits. Thank your for your contribution! Feel free to do further changes!
